### ISSUE TITLE
Incorrect average

### ISSUE THREAD

**Issue by gleue** [pilotak/MovingAverageFloat#1]
Thanks for this nice library.

I noticed the computation of the moving average is not correct. The bug is in `MovingAverageFloat.h:84` where it should be
```
_next = (_next + 1) % N;
```
instead of
```
_next = (_next + 1) & (N - 1);
```
since this does only work for `N` being a power of two -- 2, 4, 8, 16 etc.

**Comment by pilotak** [comment]
You are actually right. Thanks for spotting a bug, it comes from my https://github.com/pilotak/MovingAverage where only numbers with power of 2 are allowed. Do you want to submit a PR?
